# [2020카카오공채]자물쇠와 열쇠

HackerRank에서는 numpy 못쓰는것같아 list로 연습해야한다. list를 사용하면 인덱싱이 까다롭지만 어쩔 수 없다.

## Key idea
각 key의 회전 별로 lock을 unlock 할수있나 check 한다.
* 까다로운 부분
    1. key의 회전 구현
    2. padding을 통해 자물쇠인덱스 조절
    3. 마지막 열수있는지 checking

In [1]:
from pprint import pprint
import numpy as np
import copy

In [2]:
def solution(key, lock, verbose=False):
    def rotate(x):
        """ rotate 90 angle. """
        K = len(x)
        ret = [[0]*K for _ in range(K)]
        for i in range(K):
            for j in range(K):
                ret[j][K-1-i] = x[i][j]
        return ret # abbrevation of return
    
    N, M = len(lock), len(key)
    
    #zero padding
    pad = [[0 for i in range(N+M*2-2)] for j in range(N+M*2-2)]
    for i in range(M-1,N+M-1):
        for j in range(M-1,N+M-1):
            pad[i][j] = lock[i-M+1][j-M+1]
    if verbose: pprint(pad)

    # 4 cases of rotation.
    for _ in range(4):
        if verbose: print("{}, this is key".format(np.array(key)))
        for i in range(0, N+M-1):
            for j in range(0, N+M-1):
                if verbose: print("{} ({},{}) case".format('-'*20,i, j))
                loc = copy.deepcopy(pad) # important! 
                for x in range(M):
                    for y in range(M):
                        loc[i+x][j+y] = loc[i+x][j+y] + key[x][y]
                
                if verbose: print(np.array(loc))
                check = [False for x in range(M-1,N+M-1) for y in range(M-1,N+M-1) if loc[x][y] != 1]
                if False not in check:
                    if verbose: print("unlocked!")
                    return True
                
        if verbose: print("{} rotate key {}".format("="*30, "="*30))
        key = rotate(key)
                
    return False

In [3]:
key = [[0, 0, 0], [1, 0, 0], [0, 1, 1]]	
lock = [[1, 1, 1], [1, 1, 0], [1, 0, 1]]
solution(key, lock, verbose=True)

[[0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 1, 0, 0],
 [0, 0, 1, 1, 0, 0, 0],
 [0, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0]]
[[0 0 0]
 [1 0 0]
 [0 1 1]], this is key
-------------------- (0,0) case
[[0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 1 2 1 1 0 0]
 [0 0 1 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
-------------------- (0,1) case
[[0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 2 2 1 0 0]
 [0 0 1 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
-------------------- (0,2) case
[[0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 2 2 0 0]
 [0 0 1 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
-------------------- (0,3) case
[[0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 1 1 2 1 0]
 [0 0 1 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
-------------------- (0,4) case
[[0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 1 1 1 1 1]
 [0 0 1 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
-------------------- (1,0) case

True

## Report
1. shallow copy 를 하면 한쪽을 바꾸면 다른쪽도 바뀌어 버리므로 다음과 같이 deepcopy를 사용. <br>
    `loc = copy.deepcopy(pad)`
2. key와 lock이 겹치면 `1+1=2`가 되는데 이것을 놓쳐 시간을 많이 사용했었다. 